name: Deploy elliotkirk.com
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
    - name: Deploy elliotkirk.com
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{secrets.SSH_HOST}}
        key: ${{secrets.SSH_KEY}}
        username: ${{secrets.SSH_USERNAME}}
        passphrase: ${{secrets.SSH_PASSPHRASE}}
    
        script: |
          cd elliotkirk
          git pull
          yarn && yarn build
          echo "Deployed elliotkirk.com"
