name: Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy elliotkirk
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          passphrase: ${{secrets.SSH_PASSPHRASE}}

          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd elliotkirk
            nvm use 19.0.1
            git pull -f origin main
            yarn && yarn build
            echo "Deployed elliotkirk"
